POST http://localhost:9000/api/users HTTP/1.1
Content-type: application/json
# be careful how you copy and paste the json

 [
  {
    "description": "FULLY ASSEMBLED TIGER 80 HOT-SWAP KEYBOARD WITH PBTFANS CLASSIC HANGUL",
    "price": "$294.00",
    "img": "  //cdn.shopify.com/s/files/1/1473/3902/products/22_62c10a4e-bde8-4108-8df5-66394816a04a_1728x.jpg?v=1670302335 1728w 1728h,",
  },
    {
      "description": "FULLY ASSEMBLED TOFU60 MECHANICAL KEYBOARD WITH CEMENT GREY JAPANESE PBT KEYCAPS",
      "price": "$149.00 ",
      "img": "  //cdn.shopify.com/s/files/1/1473/3902/products/11_0c516a76-df37-4170-8cc0-3f9a02fbc648_1728x.jpg?v=1644976482 1728w 1728h,"
   }
 ]

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/638f6fff8f3aba59b7ae47a9 HTTP/1.1

###
DELETE http://localhost:9000/api/users/6386376ae66f3af195fccc75 HTTP/1.1

###
PUT http://localhost:9000/api/users/6386376ae66f3af195fccc75 HTTP/1.1
Content-type: application/json


###
